
FROM neural-fortran-base:latest

# Install packages that we want to make available at build time
RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y build-essential
RUN apt-get install -y gcc
RUN apt-get install -y gfortran
RUN apt-get install -y cmake
RUN apt-get install -y libhdf5-dev
RUN apt-get install -y curl
RUN apt-get install -y libmpich-dev
RUN apt-get install -y mpich

# Install OpenCoarrays 2.8.0
COPY external /external
RUN mkdir -p /external/OpenCoarrays/build
WORKDIR /external/OpenCoarrays/build
RUN cmake ..
RUN make
RUN make install
RUN caf --version && cafrun --version